replicaCount: 1

image:
  repository: pratikbagm/loanservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/p2p_loandb
  SPRING_JPA_HIBERNATE_DDL_AUTO: update