apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: {{ .Values.persistence.storage }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: "/mnt/data/postgres"
