apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.env.POSTGRES_USER }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD }}
