apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loan-service
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ .Release.Name }}-loan-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
