apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=         # base64 of 'username'
  SPRING_DATASOURCE_PASSWORD: UHJhdGlrQDEyMw==     # base64 of 'passwrod'
